export type Subset = 'train' | 'test' | 'validation';
export type LabelSplitPreview = { tags: string[]; intervals: TimeInterval[]; counts: Record<Subset, { rows: number; intervals: number }> };
export type CsvPreview = { columns: string[]; row_count: number; rows: string[][]; start?: string; end?: string; detected_label_column?: string | null; label_split?: LabelSplitPreview };
export type TimeSeriesDataset = {
  id: number; name: string; filename: string; columns: string[]; selected_columns: string[];
  timestamp_column: string; timestamp_format: string; row_count: number; start: string; end: string;
  label_column?: string | null;
  split_count: number; created_at: string; updated_at: string; rows?: string[][]; source_rows?: string[][];
};
export type TimeInterval = { id: string; start: string; end: string; subset: Subset; tags: string[]; row_count?: number };
export type SplitPayload = { name: string; dataset_id: number; tags: string[]; intervals: TimeInterval[] };
export type TimeSeriesSplit = SplitPayload & { id: number; dataset_name: string; created_at: string; updated_at: string };
export type DatasetPayload = { name: string; selected_columns: string[]; timestamp_column: string; timestamp_format: string; label_column?: string | null; auto_split?: boolean; split_name?: string };
export type Parameters = Record<string, number | boolean | number[]>;
export type FieldDefinition = { label: string; default: number | boolean | number[]; origin: string; reference: string; adaptation: string; minimum: number | null; maximum: number | null };
export type ModelDefinition = { kind: string; label: string; version: string; source: { reference: string; url: string }; adaptations: string[]; diagram: string[]; architecture: Record<string, FieldDefinition>; training: Record<string, FieldDefinition> };
export type SensorModel = { id: number; name: string; kind: string; config: Parameters; provenance: ModelDefinition; template_key: string | null };
export type PipelinePreview = { representation?: { shape: number[]; dimension: number; readout: string; pooling_factor?: number }; columns: string[]; sensor_count: number; sampling_interval_seconds: number; suggested_window_length: number; window_length: number; nominal_history_seconds: number; timestamp_span_seconds: number; timestamp_span_min_seconds: number | null; timestamp_span_max_seconds: number | null; detected_gaps: number; counts: Record<Subset, { rows: number; windows: number; warmup_rows: number; segments: number; gaps: number }>; errors: string[]; scaler: { minimum: number[]; maximum: number[]; denominator: number[]; constant_columns: string[] }; input_fingerprint: string };
export type PipelinePayload = { name: string; split_id: number; model_id: number; window_length: number; training: Parameters };
export type PipelineSnapshot = { dataset: { id: number; name: string }; split: TimeSeriesSplit; model: SensorModel; training: Parameters; preview: PipelinePreview; window_length: number; provenance: ModelDefinition };
export type SensorPipeline = PipelinePayload & { id: number; dataset_id: number; snapshot: PipelineSnapshot };
export type SensorRun = { id: number; pipeline_id: number; name: string; kind: string; status: string; current_step: string; epoch: number; epochs: number; train_loss: number | null; val_loss: number | null; selected_epoch: number | null; selected_metric: number | null; checkpoint_selection: string; checkpoint: Record<string, unknown>; result: Record<string, unknown>; duration_seconds: number | null; snapshot: PipelineSnapshot; error_message: string | null; processed_windows: number; total_windows: number; created_at: string; enqueued_at: string | null; started_at: string | null; ended_at: string | null; queue_rank: number | null; device: string | null; gpu_index: number | null; pid: number | null; metrics?: { epoch: number; train_loss: number; val_loss: number | null }[] };
export type ResultRow = { run_id: number; endpoint_index: number; timestamp: string; window_start: string; window_end: string; segment_id: number; subset: Subset; tags: string[]; window_score: number; endpoint_score: number; original: number; reconstruction: number; cascade?: number; second?: number; std?: number; z_sensor_ref: string };
export type ResultSeries = { raw: { timestamp: string; original: number; segment_id: number; warmup: boolean }[]; rows: ResultRow[]; total: number; offset: number; limit: number; metadata: Record<string, unknown> };
